# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artist_collection_message.proto

require 'google/protobuf'

require 'artist_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("artist_collection_message.proto", :syntax => :proto3) do
    add_message "ArtistCollectionMessage" do
      repeated :artists, :message, 1, "ArtistMessage"
    end
  end
end

ArtistCollectionMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("ArtistCollectionMessage").msgclass
