# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: venue_collection_message.proto

require 'google/protobuf'

require 'venue_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("venue_collection_message.proto", :syntax => :proto3) do
    add_message "VenueCollectionMessage" do
      repeated :artists, :message, 1, "VenueMessage"
    end
  end
end

VenueCollectionMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("VenueCollectionMessage").msgclass
